[package]
name = "myrpg"
version = "0.1.0"
authors = ["KoishiChan <qwq@koishi.top>"]
edition = "2018"

[dependencies]
regex = "1.1.6"
ref_thread_local = "0.0.0"
pretty = "0.5.2"
proc_callback = { path = "./src/proc_callback" }

[lib]
name = "myrpg"
