[package]
name = "lalr_util"
version = "0.1.0"
authors = ["KoishiChan <qwq@koishi.top>"]
edition = "2018"

[dependencies]
regex = "1.1.6"
ref_thread_local = "0.0.0"
pretty = "0.5.2"
serde = "1.0.91"
serde_json = "1.0.39"
colored = "1.8.0"
ptree = "0.2.1"    # Pretty-print tree-like structures
