[package]
name = "proc_callback"
version = "0.1.0"
authors = ["KoishiChan <qwq@koishi.top>"]
edition = "2018"

[dependencies]
proc-macro2 = "^0.4.6"
quote = "^0.6.3"
syn = "^0.15.1"

[lib]
name = "proc_callback"
proc-macro = true
